TARGET		:= jfduke3d
TITLE		:= JONOFDUKE
GIT_VERSION := $(shell git describe --abbrev=6 --dirty --always --tags)
SHADERS     := shaders

PKG_CONFIG ?= arm-vita-eabi-pkg-config
SDL_LIBS := $(shell $(PKG_CONFIG) --static --libs sdl2 vorbisfile)

LIBS = $(SDL_LIBS) -lvitaGL -lvitashark -lmathneon -lvorbisfile -lvorbis -logg  -lspeexdsp -lmpg123 \
	-lSDL2 -lc -lSceCommonDialog_stub -lSceAudio_stub -lSceLibKernel_stub -lSceShaccCg_stub \
	-lSceNet_stub -lSceNetCtl_stub -lpng -lSceDisplay_stub -lSceGxm_stub -lSceHid_stub \
	-lSceSysmodule_stub -lSceCtrl_stub -lSceTouch_stub -lSceMotion_stub -lm -lSceAppMgr_stub \
	-lSceAppUtil_stub -lScePgf_stub -ljpeg -lSceRtc_stub -lScePower_stub -lcurl -lssl -lcrypto -lz -lSceShaccCgExt -ltaihen_stub

# build locations
SRC=src
EINC=$(EROOT)/include
ELIB=$(EROOT)

#engine
EROOT ?= jfbuild
ESRC ?= $(EROOT)/src

MACTROOT ?= jfmact
AUDIOSRC = jfaudiolib/src

JFBUILDOBJS = \
	$(ESRC)/a-c.o \
  	$(ESRC)/asmprot.o \
	$(ESRC)/baselayer.o \
	$(ESRC)/cache1d.o \
	$(ESRC)/compat.o \
	$(ESRC)/crc32.o \
	$(ESRC)/defs.o \
	$(ESRC)/engine.o \
	$(ESRC)/kplib.o \
	$(ESRC)/osd.o \
	$(ESRC)/polymost.o \
	$(ESRC)/glbuild.o \
	$(ESRC)/hightile.o \
	$(ESRC)/mdsprite.o \
	$(ESRC)/polymosttex.o \
	$(ESRC)/polymosttexcache.o \
	$(ESRC)/pragmas.o \
	$(ESRC)/scriptfile.o \
	$(ESRC)/sdlayer2.o \
	$(ESRC)/textfont.o \
	$(ESRC)/smalltextfont.o \
	$(ESRC)/mmulti_null.o \
	$(ESRC)/version.o
	
JFMACTOBJS = \
	$(MACTROOT)/util_lib.o \
	$(MACTROOT)/file_lib.o \
	$(MACTROOT)/control.o \
	$(MACTROOT)/keyboard.o \
	$(MACTROOT)/mouse.o \
	$(MACTROOT)/mathutil.o \
	$(MACTROOT)/scriplib.o \
	$(MACTROOT)/animlib.o

JFAUDIOLIBOBJS= \
	$(AUDIOSRC)/drivers.o \
	$(AUDIOSRC)/fx_man.o \
	$(AUDIOSRC)/cd.o \
	$(AUDIOSRC)/multivoc.o \
	$(AUDIOSRC)/mix.o \
	$(AUDIOSRC)/mixst.o \
	$(AUDIOSRC)/pitch.o \
	$(AUDIOSRC)/vorbis.o \
	$(AUDIOSRC)/music.o \
	$(AUDIOSRC)/midi.o \
	$(AUDIOSRC)/driver_sdl.o \
	$(AUDIOSRC)/driver_nosound.o \
	$(AUDIOSRC)/asssys.o

GAMEOBJS = \
	$(SRC)/game.o \
	$(SRC)/actors.o \
	$(SRC)/gamedef.o \
	$(SRC)/global.o \
	$(SRC)/menues.o \
	$(SRC)/player.o \
	$(SRC)/premap.o \
	$(SRC)/sector.o \
	$(SRC)/rts.o \
	$(SRC)/config.o \
	$(SRC)/osdfuncs.o \
	$(SRC)/osdcmds.o \
	$(SRC)/grpscan.o \
	$(SRC)/sounds.o

OBJS     := $(GAMEOBJS) $(JFBUILDOBJS) $(JFAUDIOLIBOBJS) $(JFMACTOBJS)

PREFIX  = arm-vita-eabi
CC      = $(PREFIX)-gcc
CXX      = $(PREFIX)-g++
CFLAGS  = -fsigned-char -Wl,-q,--wrap,fopen,--wrap,opendir,--wrap,open,--wrap,access,--wrap,getcwd,--wrap,chdir \
	-O3 -g -fno-optimize-sibling-calls -DUSE_POLYMOST -DUSE_OPENGL=USE_GLES2\
	-ffast-math -mtune=cortex-a9 -mfpu=neon -DHAVE_VORBIS -Isrc \
	-Ijfbuild/include -Ijfmact -Ijfaudiolib/include -DVITA -DHAVE_SDL \
	-Wno-implicit-function-declaration -I$(VITASDK)/$(PREFIX)/include/SDL2

ifeq ($(NAM),1)
CFLAGS += -DNAM
endif
	
CXXFLAGS  = $(CFLAGS) -fno-exceptions -std=gnu++11
ASFLAGS = $(CFLAGS)
LDFLAGS += -Wl,--defsym=__sce_headroom=0x2000

ifeq ($(NAM),1)
all: $(TARGET).bin

$(TARGET).bin: $(TARGET).velf
	vita-make-fself -c -s $< build/$(TARGET).bin
else
all: $(TARGET).vpk

$(TARGET).vpk: $(TARGET).velf
	vita-make-fself -c -s $< build/eboot.bin
	vita-mksfoex -s TITLE_ID=$(TITLE) -d ATTRIBUTE2=12 "JFDuke3D" param.sfo
	vita-pack-vpk -s param.sfo -b build/eboot.bin \
		--add build/sce_sys/icon0.png=sce_sys/icon0.png \
		--add build/sce_sys/livearea/contents/bg.png=sce_sys/livearea/contents/bg.png \
		--add build/sce_sys/livearea/contents/startup.png=sce_sys/livearea/contents/startup.png \
		--add build/sce_sys/livearea/contents/template.xml=sce_sys/livearea/contents/template.xml \
		--add build/jfduke3d.bin=jfduke3d.bin \
		$(TARGET).vpk
endif

%.velf: %.elf
	cp $< $<.unstripped.elf
	$(PREFIX)-strip -g $<
	vita-elf-create $< $@

$(TARGET).elf: $(OBJS)
	$(CXX) $(CXXFLAGS) -pthread $^ $(LDFLAGS) $(LIBS) -o $@

clean:
	@rm -rf $(TARGET).velf $(TARGET).elf $(OBJS) $(TARGET).elf.unstripped.elf $(TARGET).vpk build/eboot.bin ./param.sfo
